iti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
]

todo/urls.py
from django.urls import path, re_path

from .views import index, todo_list, todo_detail, todo_delete, todo_update

app_name = 'todo'

urlpatterns = [
    path('index', index, name='index'),
    path('list', todo_list, name='todo-list'),

    # Example for passing parameters as positional argument
    # re_path('task/<?P[0-9]{3}>', todo_detail, name='todo-detail'),

    path('task/<int:task_id>/update', todo_update, name='todo-update'),
    path('task/<int:task_id>/view', todo_detail, name='todo-detail'),
    path('task/<int:task_id>/delete', todo_delete, name='todo-delete'),
]

todo/models.py
from django.db import models

# Create your models here.

todo/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse

from django.http.response import JsonResponse

from pprint import pprint


# Create your views here.

def index(request):
    return render(request, 'main/base_layout.html')


my_task_list = [
    {
        'index': 0,
        'id': 1,
        'name': 'Interstellar',
        'priority': 1,
        'description': "Interstellar is about Earth's last chance to find a habitable planet before a lack of resources causes the human race to go extinct. The film's protagonist is Cooper (Matthew McConaughey), a former NASA pilot who is tasked with leading a mission through a wormhole to find a habitable planet in another galaxy.",
    },
    {
        'index': 1,
        'id': 2,
        'name': 'Avatar ',
        'priority': 4,
        'description': "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home. When his brother is killed in a robbery, paraplegic Marine Jake Sully decides to take his place in a mission on the distant world of Pandora.",
    },
    {
        'index': 2,
        'id': 3,
        'name': 'Harry Potter',
        'priority': 2,
        'description': "Throughout the series, Harry is described as having his father's perpetually untidy black hair, his mother's bright green eyes, and a lightning bolt-shaped scar on his forehead. He is further described as small and skinny for his age with a thin face and knobbly knees, and he wears Windsor glasses.",

    },
]


def _get_target_task(target_id):
    # Filter the list based on the task id sent and compare it toward each dictionary item in the list
    filter_result = filter(lambda d: d.get('id') == target_id, my_task_list)
    final_list = list(filter_result)

    # Getting index of the required task from my_task_list
    index_of_task = my_task_list.index(final_list[0])

    return index_of_task


def todo_list(request):
    my_context = {'task_list': my_task_list, }
    return render(request, 'todo/todo_list.html', context=my_context)


def todo_update(request, **kwargs):
    task_id = kwargs.get('task_id')
    index_to_update = _get_target_task(task_id)
    my_task_list[index_to_update]['name'] = 'Updated {}'.format(my_task_list[index_to_update].get('name'))

    return redirect('todo:todo-list')


def todo_delete(request, **kwargs):
    task_id = kwargs.get('task_id')

    index_to_delete = _get_target_task(task_id)

    if my_task_list:
        my_task_list.pop(index_to_delete)

    return redirect('todo:todo-list')


def todo_detail(request, *args, **kwargs):

    # NEW CONTEXT
    task_id = kwargs.get('task_id')

    task_index = _get_target_task(task_id)

    my_task_dictionary = my_task_list[task_index]

    my_context = {
        'task_id': my_task_dictionary.get('id'),
        'task_name': my_task_dictionary.get('name'),
        'task_priority': my_task_dictionary.get('priority'),
        'task_description': my_task_dictionary.get('description')
    }

    return render(request, 'todo/todo_detail.html', context=my_context)

todo/templates/todo/todo_detail.html
{% extends 'main/base_layout.html' %}
{% load my_custom_tags %}


{% block main-content %}


{% my_simple_tag user as my_simple_variable %}

<h5>  {{my_simple_variable}} </h5>


<h1> Welcome To Our ToDo Detail </h1>

<table class="table table-condensed text-center font-weight-bold text-white">
    <thead>
    <tr>
        <td>Task ID</td>
        <td>TasK Name</td>
        <td>Priority</td>
        <td>Description</td>
    </tr>
    </thead>

    <tbody>
    <tr {% if task_priority > 3 %} style="color:#fff" {% else %} style="color:#000" {% endif %} >
        <td>{{task_id}}</td>

        <td>{{task_name | name_filter_cleaner }}</td>

        <td>{{task_priority}}</td>
        <td>{{task_description | truncatewords:3}}</td>
    </tr>
    </tbody>
</table>

{% endblock %}

{# Example for if condition #}

{% if task_priority > 3 %}
    <h1> HIGH PRIORITY TASK</h1>
{% else %}
    <h1> LOW PRIORITY TASK</h1>
{% endif %}


<a href="{% url 'todo:index' %}">Back to Index</a>
<br/>
<a href="{% url 'todo:todo-list' %}">Back to list</a>

<h1>INDEX {% url 'todo:index' %}</h1>

<h1>List {% url 'todo:todo-list' %}</h1>

todo/templates/todo/todo_list.html
{% extends 'main/base_layout.html' %}


{# override block title #}

{% block title %}
    TODO Task List
{% endblock %}


{# override block main-content #}

{% block main-content %}

{# example about for loop #}
<table class="table table-condensed text-center font-weight-bold text-white">
    <thead>
    <tr>
        <td> ID</td>
        <td> Name</td>
        <td>Priority</td>
        <td>Description</td>
        <td>Actions</td>
    </tr>
    </thead>

    <tbody>
        {% for task in task_list %}
    <tr {% if task.priority > 3 %} style="color:#fff" {% else %} style="color:#000" {% endif %} >
        <td>{{task.id}}</td>

        <td>{{ task.name }}</td>
        <td>{{task.priority}}</td>
        <td>{{task.description | truncatewords:50 | title}}</td>
        <td>
            <a class="btn btn-success m-3" href="{% url 'todo:todo-detail' task.id %}">View</a>
            <a class="btn btn-info m-3" href="{% url 'todo:todo-update' task.id %}">Update</a>
            <a class="btn btn-danger m-3" href="{% url 'todo:todo-delete' task.id %}">Delete</a>

        </td>
    </tr>
        {% empty %}
    <tr>
        <td colspan="3" class="text-center"> Well Done, You finish all Tasks.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{%endblock%}